"""Constants for the eWeLink IoT integration."""

import os
from typing import Final

from homeassistant.const import Platform

# Dev mode
DEV_MODE = os.getenv("HA_DEV_MODE") == "1"

DOMAIN: Final = "ewelink_iot"
PLATFORMS: Final = [
    Platform.BINARY_SENSOR,
    Platform.EVENT,
    Platform.LIGHT,
    Platform.SELECT,
    Platform.SENSOR,
    Platform.SWITCH,
]

EWELINK_API_CN: Final = "https://cn-apia.coolkit.cn"
EWELINK_API_AS: Final = "https://as-apia.coolkit.cc"
EWELINK_API_US: Final = "https://us-apia.coolkit.cc"
EWELINK_API_EU: Final = "https://eu-apia.coolkit.cc"
EWELINK_API_IR: Final = "https://ir-apia.coolkit.cc"
EWELINK_API_TEST: Final = "https://test-apia.coolkit.cn"

EWELINK_WS_RESOURCE_CN = "https://cn-dispa.coolkit.cn"

# 15 days
EWELINK_API_AT_EXPIRED_TS = 15 * 24 * 60 * 60 * 1000

APP_ID: Final = "oc3tvAdJPmaVOKrLv0rjCC0dzub4bbnD"
APP_SECRET: Final = "V0LmoW0cd2cg38i1eIM0P5Z29GjES4PA"

WS_CLIENT = "ws_client"
API_CLIENT = "api_client"
COORDINATOR = "coordinator"

# Config entry keys
CONF_ACCOUNT: Final = "account"
CONF_APP_ID: Final = "app_id"
CONF_APP_SECRET: Final = "app_secret"
CONF_REGION: Final = "region"
CONF_COUNTRY_CODE: Final = "country_code"

# Device types
DEVICE_TYPE_SWITCH: Final = "switch"

# Websocket message types
WS_MSG_TYPE_HANDSHAKE: Final = "handshake"
WS_MSG_ACTION: Final = "action"
WS_MSG_ACTION_UPDATE: Final = "update"
WS_MSG_ACTION_SYSMSG: Final = "sysmsg"
WS_MSG_ACTION_USER_ONLINE: Final = "userOnline"
WS_USER_AGENT: Final = "pc_ewelink"

# re pattren
RE_EMAIL_PATTREN = r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"

# top domain
CN: Final = "cn"
CC: Final = "cc"

# Regions
REGION_CN: Final = "cn"
REGION_AS: Final = "as"
REGION_US: Final = "us"
REGION_EU: Final = "eu"
REGION_IR: Final = "ir"
REGION_TEST: Final = "test"
REGION_DEFAULT: Final = "+86"
REGIONS_MAP: Final = [
    {CONF_COUNTRY_CODE: "+86", CONF_REGION: REGION_CN},
    {CONF_COUNTRY_CODE: "+93", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+355", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+213", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+376", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+244", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+1264", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+247", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+1268", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+54", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+374", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+297", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+61", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+43", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+994", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+1242", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+973", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+880", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+1246", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+375", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+32", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+501", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+229", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+1441", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+975", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+591", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+387", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+267", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+55", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+673", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+359", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+226", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+257", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+855", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+237", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+1", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+238", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+1345", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+236", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+235", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+56", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+57", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+269", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+242", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+243", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+682", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+506", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+225", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+385", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+53", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+357", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+420", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+45", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+253", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+1767", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+1809", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+593", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+20", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+503", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+372", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+251", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+298", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+679", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+358", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+33", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+594", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+689", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+241", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+220", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+995", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+49", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+233", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+350", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+30", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+299", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+1473", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+590", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+1671", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+502", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+240", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+44", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+224", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+592", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+509", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+504", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+852", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+95", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+36", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+354", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+91", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+62", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+98", CONF_REGION: REGION_IR},
    {CONF_COUNTRY_CODE: "+964", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+353", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+44", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+972", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+39", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+1876", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+81", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+44", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+962", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+7", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+254", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+383", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+965", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+996", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+856", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+371", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+961", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+266", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+231", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+218", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+423", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+370", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+352", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+853", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+389", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+261", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+265", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+60", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+960", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+223", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+356", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+596", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+222", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+230", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+262", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+52", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+373", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+377", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+976", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+382", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+1664", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+212", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+258", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+264", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+977", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+31", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+599", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+687", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+64", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+505", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+227", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+234", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+47", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+968", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+92", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+970", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+507", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+675", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+595", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+51", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+63", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+48", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+351", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+1", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+974", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+262", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+40", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+7", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+250", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+684", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+685", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+378", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+239", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+966", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+221", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+381", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+248", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+232", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+65", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+421", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+386", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+27", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+82", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+34", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+94", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+1869", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+1758", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+1784", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+249", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+597", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+268", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+46", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+41", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+963", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+886", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+992", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+255", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+66", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+670", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+228", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+676", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+1868", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+216", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+90", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+993", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+1649", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+256", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+380", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+971", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+44", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+1", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+598", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+998", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+678", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+58", CONF_REGION: REGION_US},
    {CONF_COUNTRY_CODE: "+84", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+1340", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+967", CONF_REGION: REGION_AS},
    {CONF_COUNTRY_CODE: "+260", CONF_REGION: REGION_EU},
    {CONF_COUNTRY_CODE: "+263", CONF_REGION: REGION_EU},
]

EWELINK_API_MAP: Final = {
    REGION_CN: EWELINK_API_CN,
    REGION_AS: EWELINK_API_AS,
    REGION_EU: EWELINK_API_EU,
    REGION_US: EWELINK_API_US,
    REGION_IR: EWELINK_API_IR,
    REGION_TEST: EWELINK_API_TEST,
}
